stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the package..."
    - python setup.py sdist bdist_wheel

deploy:
  stage: deploy
  script:
    - echo "Deploying to PyPI..."
    - pip install twine
    - twine upload dist/* -u __token__ -p $PYPI_TOKEN
  only:
    - /^v[0-9]+(\.[0-9]+)*$/
